spring.application.name=measurement-tracker1
spring.datasource.url=jdbc:hsqldb:file:./data/measurementdb
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true