package org.example.measurementtrackerclean.controller;
import jakarta.validation.Valid;import lombok.RequiredArgsConstructor;import org.example.measurementtrackerclean.dto.*;import org.example.measurementtrackerclean.service.CoreServices;import org.springframework.format.annotation.DateTimeFormat;import org.springframework.http.HttpStatus;import org.springframework.web.bind.annotation.*;import org.springframework.web.multipart.MultipartFile;
import java.security.Principal;import java.time.LocalDateTime;import java.util.*;
@RestController @RequiredArgsConstructor
public class ApiController {
 private final CoreServices s;
 @PostMapping("/auth/register") @ResponseStatus(HttpStatus.CREATED) public AuthDtos.AuthResponse register(@Valid @RequestBody AuthDtos.RegisterRequest r){return s.register(r);} 
 @PostMapping("/auth/login") public AuthDtos.AuthResponse login(@Valid @RequestBody AuthDtos.LoginRequest r){return s.login(r);} 
 @GetMapping("/users/me") public Map<String,Object> me(Principal p){var u=s.me(p.getName()); return Map.of("id",u.getId(),"username",u.getUsername(),"createdAt",u.getCreatedAt());}
 @PostMapping("/meters") public MeterDtos.MeterResponse createMeter(Principal p,@Valid @RequestBody MeterDtos.MeterRequest r){return s.createMeter(p.getName(),r);} @GetMapping("/meters") public List<MeterDtos.MeterResponse> meters(Principal p){return s.meters(p.getName());} @GetMapping("/meters/{id}") public MeterDtos.MeterResponse meter(Principal p,@PathVariable Long id){return s.meter(p.getName(),id);} @PutMapping("/meters/{id}") public MeterDtos.MeterResponse updateMeter(Principal p,@PathVariable Long id,@Valid @RequestBody MeterDtos.MeterRequest r){return s.updateMeter(p.getName(),id,r);} @DeleteMapping("/meters/{id}") @ResponseStatus(HttpStatus.NO_CONTENT) public void delMeter(Principal p,@PathVariable Long id){s.deleteMeter(p.getName(),id);} 
 @PostMapping("/readings/manual") public ReadingDtos.ReadingResponse manual(Principal p,@Valid @RequestBody ReadingDtos.ManualReadingRequest r){return s.manual(p.getName(),r);} @GetMapping("/readings") public List<ReadingDtos.ReadingResponse> readings(Principal p){return s.readings(p.getName());} @GetMapping("/readings/{id}") public ReadingDtos.ReadingResponse reading(Principal p,@PathVariable Long id){return s.reading(p.getName(),id);} @GetMapping("/readings/meter/{meterId}") public List<ReadingDtos.ReadingResponse> meterReadings(Principal p,@PathVariable Long meterId){return s.byMeter(p.getName(),meterId);} @GetMapping("/readings/history") public List<ReadingDtos.ReadingResponse> history(Principal p,@RequestParam Long meterId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) LocalDateTime from,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) LocalDateTime to){return s.history(p.getName(),meterId,from,to);} 
 @PostMapping(value="/ocr/tasks",consumes="multipart/form-data") @ResponseStatus(HttpStatus.ACCEPTED) public Map<String,Object> ocrTask(Principal p,@RequestParam Long meterId,@RequestParam @DateTimeFormat(iso=DateTimeFormat.ISO.DATE_TIME) LocalDateTime timestamp,@RequestPart MultipartFile file){return s.queueTask(p.getName(),meterId,timestamp,file);} @GetMapping("/ocr/tasks") public List<?> tasks(Principal p){return s.taskList(p.getName());} @GetMapping("/ocr/tasks/{id}") public Object task(Principal p,@PathVariable Long id){return s.task(p.getName(),id);} }
